# # ==============================================================================
# #
# #   _____ ____  ________________     __  ___________________  _____________
# #  / ___// __ \/ ____/ ____/ __ \   /  |/  / ____/_  __/ __ \/  _/ ____/   |
# #  \__ \/ /_/ / __/ / __/ / / / /  / /|_/ / __/   / / / /_/ // // /   / /| |
# # ___/ / ____/ /___/ /___/ /_/ /  / /  / / /___  / / / _, _// // /___/ ___ |
# #/____/_/   /_____/_____/_____/  /_/  /_/_____/ /_/ /_/ |_/___/\____/_/  |_|
# #
# #                           www.speedmetrica.com
# #
# # ==============================================================================
# # Comparing calculated signal from SM_curvature with data generated by motec i2

# # Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_from_i2 = 'interlagos_corner_data.csv'
data_from_lts = '../track_coordinates/turn_radius.csv'

df_lts = pd.read_csv(data_from_lts, sep=',')
df_i2 = pd.read_csv(data_from_i2, sep=',', low_memory=False, skiprows=13)

fig, ax = plt.subplots(2, 1, figsize=(10, 5))
plot_1 = ax[0].plot(df_lts['Corner Radius Norm'])

plt.show()
